on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
name: Website
jobs:
  website:
    runs-on: ubuntu-latest
    name: Website
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          LATEST=$(find ./results/* -type d -prune | tail -n 1)
          yarn
          node src/report $LATEST > ./www/src/report.json
          cp $LATEST/* ./www/public/report/
          cd www
          yarn
          CI=false yarn build
          touch build/.nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: www/build
